### ISSUE TITLE
Recipe advancement + animated texture

### ISSUE THREAD

**Issue by anoomolu** [InValidFire/kiln#4]
Hiya! I noticed there wasn't a recipe advancement that would let you discover the kiln recipe, so I quickly made one based on the Blast Furnace recipe. Should just be in a json in data/advancements/recipes.

```
{
  "parent": "minecraft:recipes/root",
  "criteria": {
    "has_bricks": {
      "conditions": {
        "items": [
          {
            "items": [
              "minecraft:bricks"
            ]
          }
        ]
      },
      "trigger": "minecraft:inventory_changed"
    },
    "has_the_recipe": {
      "conditions": {
        "recipe": "ember_kiln:kiln_crafting"
      },
      "trigger": "minecraft:recipe_unlocked"
    }
  },
  "requirements": [
    [
      "has_bricks",
      "has_the_recipe"
    ]
  ],
  "rewards": {
    "recipes": [
      "ember_kiln:kiln_crafting"
    ]
  },
  "sends_telemetry_event": false
}
```

I also made an animated kiln texture, based on Lily's [animated furnace resource pack.](https://legacy.curseforge.com/minecraft/texture-packs/animated-furnace)

File name is kiln_front_on.
![kiln_front_on](https://github.com/InValidFire/kiln/assets/77850233/bcfc1e91-6097-4f9f-8628-92f26260d828)
Kiln_front_on.mcmeta:
```
{
  "animation": {
    "interpolate": false,
    "frametime": 4
  }
}
```

**Comment by LadyEmby** [comment]
Oh wow! Thanks a lot for doing this! I'll get these changes merged into the mod ASAP. 

One note, the animated kiln texture pack appears to have All Rights Reserved, so I'm unsure of my rights to modify or use their assets in my projects. I've sent them a message and am awaiting a response on that. 

I'll definitely include the advancement though. :)

**Comment by anoomolu** [comment]
Yeah I was wary of the ARR part, sorry about that I probably should have asked them myself >.<

**Comment by Lylythii** [comment]
Just chiming in here to confirm that this is perfectly fine with me! Though would've preferred to be asked *ahead* of time.
No problems either way. <3
