### ISSUE TITLE
A couple of things

### ISSUE THREAD

**Issue by anoomolu** [InValidFire/kiln#5]
Hiya! I'm sorry for yet another issue, I promise this is the last one!

I had a question/some points regarding this mod:
- Would charcoal, popped chorus, lime/green dye and wet sponge drying recipes be out of place? I've got recipes for them in my custom pack and thought they might be a good fit for the mod, at least the charcoal one since kilns are used to make it irl
- I'm getting a bit of logspam when loading recipes (Unknown recipe category: ember_kiln:kiln/ember_kiln:glass for example). Harmless error so no worries if that isn’t really an issue.

Thanks for making this mod, it's super useful for processing resources for big builds

**Comment by LadyEmby** [comment]
The logspam is unfortunately a side-effect of Mojang's implementation of the recipe book, I will be adding charcoal to the recipes though! I feel like the other recipes would be out of place for this item though.
