### ISSUE TITLE
Backport animated kiln texture to 1.20.1

### ISSUE THREAD

**Issue by anoomolu** [InValidFire/kiln#7]
Hiya, hope you're doing well.

I just was wondering if the animated texture could be backported to 1.20.1, or if you could permit me to use it in a resource pack?
Cheers.

**Comment by LadyEmby** [comment]
I can backport things yeah, as it seems 1.20.1 is a major modded version, it'd probably be beneficial.

**Comment by LadyEmby** [comment]
The deed is done. :)

https://modrinth.com/mod/embers-kiln/version/8mZHdGav
